# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_label', models.CharField(max_length=64, verbose_name='Printed Label')),
                ('vendor_name', models.CharField(max_length=64, verbose_name='Vendor Name')),
                ('pin_number', models.CharField(max_length=64, verbose_name='Vendor Pin Number')),
                ('serial_number', models.CharField(max_length=64, verbose_name='Vendor Serial Number')),
                ('vendor_oui', models.CharField(max_length=64, verbose_name='Vendor OUI')),
                ('manufactorer', models.CharField(max_length=64, verbose_name='Manufactorer')),
                ('form_factor', models.CharField(max_length=64, verbose_name='Form Factor')),
                ('speed', models.CharField(max_length=64, verbose_name='Default Speed')),
                ('mod_type', models.CharField(max_length=64, verbose_name='Module Type')),
                ('length', models.SmallIntegerField(verbose_name='Length')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=64, verbose_name='Platform Name')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField(auto_now=True, verbose_name='Date Tested')),
                ('qsa_used', models.BooleanField(verbose_name='QSA Used?')),
                ('speed', models.CharField(max_length=64, verbose_name='Speed Tested')),
                ('bug_id', models.URLField(verbose_name='Bug-ID')),
                ('test_passed', models.BooleanField(verbose_name='Pass?')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.CableModule')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Platform')),
            ],
        ),
    ]
