# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablemodule',
            name='manufactorer',
        ),
        migrations.AddField(
            model_name='cablemodule',
            name='vendor_rev',
            field=models.CharField(default='X', max_length=64, verbose_name='Vendor Rev'),
            preserve_default=False,
        ),
    ]
