# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20160705_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='date_tested',
            field=models.DateField(auto_now_add=True, verbose_name='Date Tested'),
        ),
    ]
