# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20160705_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='bug_id',
            field=models.URLField(null=True, verbose_name='Bug-ID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='date_tested',
            field=models.DateField(default=datetime.date(2016, 7, 5), verbose_name='Date Tested'),
        ),
    ]
